"""
Content-based Persistent Disk Cache for Vision Analysis.

Caches Qwen2.5-VL vision analysis keyed by SHA256 of the raw image bytes.
Independent of image filename or source document location.
"""
import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

from app.config.logging import get_logger

logger = get_logger(__name__)


class VisionCache:
    """
    Disk-based cache for diagram vision analysis results.
    Keyed by SHA256 digest of the image bytes.
    """

    def __init__(self, cache_dir: str | Path = "./data/processed/vision_cache") -> None:
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def compute_hash(image_path: str | Path, model_version: str = "v1", prompt_version: str = "v1", resize_dim: int = 1024) -> str:
        """
        Compute SHA256 hex digest of image file bytes combined with execution metadata.
        This ensures that changing model versions, prompts, or resize parameters busts the cache.
        """
        path = Path(image_path)
        hasher = hashlib.sha256()
        
        # 1. Hash the configuration metadata
        metadata = f"{model_version}_{prompt_version}_{resize_dim}".encode("utf-8")
        hasher.update(metadata)
        
        # 2. Hash the actual image bytes
        with open(path, "rb") as f:
            while chunk := f.read(65536):
                hasher.update(chunk)
        return hasher.hexdigest()

    def _get_cache_path(self, content_hash: str) -> Path:
        return self.cache_dir / f"{content_hash}.json"

    def get(self, content_hash: str, valid_models: list[str] | None = None) -> dict[str, Any] | None:
        """
        Retrieve cached analysis by image content hash.
        If valid_models is provided, ensures the cached result was generated by one of them.
        Returns None on cache miss or corrupted entry.
        """
        cache_path = self._get_cache_path(content_hash)
        if not cache_path.is_file():
            return None

        try:
            with open(cache_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if not isinstance(data, dict):
                return None
            if valid_models is not None:
                cached_model = data.get("model_used")
                if not cached_model or cached_model not in valid_models:
                    return None
            return data
        except Exception as exc:
            logger.warning("vision.cache.read_error", hash=content_hash, error=str(exc))
            return None

    def store(self, content_hash: str, analysis: dict[str, Any]) -> None:
        """
        Store successful analysis in disk cache atomically.
        Does NOT store failed, skipped, or timed-out results.
        """
        if not isinstance(analysis, dict):
            return

        status = analysis.get("status", "ok")
        if status.upper() in {"FAILED", "TIMEOUT", "SKIPPED"}:
            return

        cache_path = self._get_cache_path(content_hash)
        temp_fd, temp_path = tempfile.mkstemp(
            dir=str(self.cache_dir),
            prefix=f"{content_hash}_",
            suffix=".tmp",
        )
        try:
            with os.fdopen(temp_fd, "w", encoding="utf-8") as f:
                json.dump(analysis, f, indent=2)
            os.replace(temp_path, cache_path)
            logger.info("vision.cache.stored", hash=content_hash, path=str(cache_path))
        except Exception as exc:
            logger.error("vision.cache.write_error", hash=content_hash, error=str(exc))
            if os.path.exists(temp_path):
                try:
                    os.unlink(temp_path)
                except OSError:
                    pass

    def has(self, content_hash: str) -> bool:
        """Check if a valid cache entry exists for the given hash."""
        return self.get(content_hash) is not None
